name: "highstreet_tenure"
version: "1.0.0"

config-version: 2

profile: "highstreet_local"

# Define model paths – you can add staging, marts etc. later
model-paths: ["models"]

models:
  highstreet_tenure:
    +schema: analytics  # use a dedicated schema to avoid cluttering public
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
