FROM postgis/postgis:16-3.4  

# Environment variables for the default Postgres super-user
ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres \
    POSTGRES_DB=highstreet

# Expose the default Postgres port
EXPOSE 5432

